[default.extend-identifiers]
# used to store multi-array slice to Node.Data.
datas = "datas"

[files]
extend-exclude = ["src/io/glob_test.zig", "src/zig/0.14.1/tokenizer.zig", "build.zig.zon"]

[type.zig]
extend-glob = ["*.zig", "*.zog"]
check-file = true

[type.zig.extend-words]
"hlep" = "hlep" # "--hlep" is checked for in options parsing, used as --help alias.
